import {AlertTriangle, X, ShieldAlert } from 'lucide-react';
import { useContext, useEffect, useState } from 'react';
import { AppContext } from '../../context/Context';
import axios from 'axios';
import { toast } from 'react-toastify';
import { jwtDecode } from 'jwt-decode';

const RejectProject = ({ projectId, report, reportRef }) => {

  const { setIsRejected, handleAllProjects } = useContext(AppContext)
  const [loading, setLoading] = useState(false)
  const [rejected, setRejected] = useState(false)
  const [rejectionReason, setRejectionReason] = useState('')

  const handleReject = async () => {

    if (!reportRef) return toast.error("Report content not ready");

    const currentReportContent = reportRef;
    const reportHtml = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>Rejection Report - ${report.fileName}</title>
      </head>
      <body class="bg-slate-50 p-10 font-sans">
        <div class="max-w-4xl mx-auto bg-white p-10 rounded-4xl shadow-sm border border-slate-200">
          <div class="mb-8 border-b border-slate-100 pb-6">
            <h1 class="text-3xl font-black text-rose-600">Rejection Feedback</h1>
            <p class="text-slate-500 mt-2 font-bold uppercase tracking-widest text-xs">
              File: ${report.fileName}
            </p>
          </div>
          
          ${currentReportContent} 

          <div class="mt-10 pt-6 border-t border-slate-100 text-[10px] text-slate-400 text-center uppercase font-bold tracking-widest">
            Generated by NuradPlag AI Detection System
          </div>
        </div>
      </body>
    </html>
    `;

    const blob = new Blob([reportHtml], { type: 'text/html' });
    const formData = new FormData();

    formData.append('reportHtml', blob, `Report_${report.fileName}.html`);
    formData.append('projectId', projectId);
    formData.append('reason', rejectionReason);
    formData.append('userId', report.userId);

    setLoading(true)

    try {
      const response = await axios.post(`/reject/${projectId}`, formData);
      if(response.data){
        toast.success(response.data.message);
      }
      setRejectionReason("");
      await handleAllProjects();
      setIsRejected(false)
    } catch (err) {
      console.log(err)
      toast.error("Error sending rejection.");
    }finally{
      setLoading(false)
    }
  };

  useEffect(() => {
    const getUserProject = async () => {
      try {
        const response = await axios.put(`/filter/project/`, {
          projectId: projectId
        })
        if (response) {
          setRejected(response.data.rejected)
        }
      } catch (err) {
        console.log(err)
      }
    }
    getUserProject()
  }, [])

  return (
    <div className="fixed inset-0 z-500 flex items-center justify-center p-4 bg-slate-900/60 animate-in fade-in duration-300">

      <div className="bg-white w-full max-w-sm rounded-[2.5rem] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300 relative">

        <div className="h-2 w-full bg-red-500" />

        <div className="p-7">
          <button
            onClick={() => setIsRejected(false)}
            className="absolute top-6 right-6 p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-400"
          >
            <X size={20} />
          </button>

          <div className="flex flex-col items-center text-center gap-3">
            <div className="w-16 h-16 bg-rose-50 rounded-2xl flex items-center justify-center text-rose-600 mb-2">
              <AlertTriangle size={32} />
            </div>

            <h3 className="text-xl font-black text-slate-900">Reject Submission?</h3>

            <p className="text-slate-500 text-[10px] leading-relaxed">
              You are rejecting <span className="font-bold text-slate-800">{report && report.fileName}</span>.
              The student will receive an email of the report result
            </p>
          </div>

          <div className="mt-5">
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest ml-2 mb-1 block">
              Reason for Rejection
            </label>
            <textarea
              value={rejectionReason}
              onChange={(e) => setRejectionReason(e.target.value)}
              placeholder="E.g., High AI probability in Chapter 2, please revise and resubmit..."
              className="w-full p-4 bg-slate-50 border border-slate-100 rounded-2xl text-xs text-slate-700 focus:outline-none focus:ring-2 focus:ring-rose-500/20 resize-none h-24 transition-all placeholder:text-slate-300"
            />
          </div>

          {/* Warning Note */}
          <div className="mt-4 p-3 bg-rose-50 rounded-2xl border border-rose-100 flex gap-3">
            <ShieldAlert size={18} className="text-rose-600 shrink-0" />
            <p className="text-[9px] text-rose-700 font-medium leading-tight">
              This action will mark the project as "Rejected" in the database and notify the student immediately.
            </p>
          </div>

          {/* Actions */}
          <div className="mt-8 flex items-center justify-between gap-3">
            <button
              className={`w-full p-3 bg-red-600 hover:bg-red-700 text-white font-bold rounded-2xl transition-all shadow-lg shadow-red-200 text-xs active:scale-95 disabled:opacity-50 disabled:active:scale-100`}
              onClick={handleReject}
              disabled={loading || rejected}
            >
              {loading ? 'Processing...' : rejected ? 'Already Rejected' : 'Confirm Rejection'}
            </button>

            <button
              className="w-full p-3 bg-white border border-slate-200 text-slate-500 font-bold rounded-2xl transition-all hover:bg-slate-50 text-xs active:scale-95"
              onClick={() => setIsRejected(false)}
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RejectProject;